name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # 👈 Change if your default branch is different
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE-SKY-043D71300-2 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Required for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "/"           # Root folder with index.html
          api_location: ""            # No backend API
          output_location: "."        # Same as app_location
          skip_app_build: true        # ✅ Skip Node.js build process
